// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0-devel
// 	protoc        v3.11.4
// source: micropayment.proto

package micropayment

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SignedTxn struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Receiver     string    `protobuf:"bytes,1,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Amount       float64   `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	BillingCycle int32     `protobuf:"varint,3,opt,name=billing_cycle,json=billingCycle,proto3" json:"billing_cycle,omitempty"`
	TxnHash      string    `protobuf:"bytes,4,opt,name=txn_hash,json=txnHash,proto3" json:"txn_hash,omitempty"`
	Mtdt         *Metadata `protobuf:"bytes,5,opt,name=mtdt,proto3" json:"mtdt,omitempty"`
}

func (x *SignedTxn) Reset() {
	*x = SignedTxn{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micropayment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SignedTxn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedTxn) ProtoMessage() {}

func (x *SignedTxn) ProtoReflect() protoreflect.Message {
	mi := &file_micropayment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedTxn.ProtoReflect.Descriptor instead.
func (*SignedTxn) Descriptor() ([]byte, []int) {
	return file_micropayment_proto_rawDescGZIP(), []int{0}
}

func (x *SignedTxn) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *SignedTxn) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SignedTxn) GetBillingCycle() int32 {
	if x != nil {
		return x.BillingCycle
	}
	return 0
}

func (x *SignedTxn) GetTxnHash() string {
	if x != nil {
		return x.TxnHash
	}
	return ""
}

func (x *SignedTxn) GetMtdt() *Metadata {
	if x != nil {
		return x.Mtdt
	}
	return nil
}

type Metadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vals map[string]*Metadata_MtdtVal `protobuf:"bytes,1,rep,name=vals,proto3" json:"vals,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micropayment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_micropayment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_micropayment_proto_rawDescGZIP(), []int{1}
}

func (x *Metadata) GetVals() map[string]*Metadata_MtdtVal {
	if x != nil {
		return x.Vals
	}
	return nil
}

type Metadata_MtdtVal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IncludeSignature bool `protobuf:"varint,1,opt,name=include_signature,json=includeSignature,proto3" json:"include_signature,omitempty"`
	// Types that are assignable to Val:
	//	*Metadata_MtdtVal_IntVal
	//	*Metadata_MtdtVal_StrVal
	Val isMetadata_MtdtVal_Val `protobuf_oneof:"Val"`
}

func (x *Metadata_MtdtVal) Reset() {
	*x = Metadata_MtdtVal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micropayment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Metadata_MtdtVal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata_MtdtVal) ProtoMessage() {}

func (x *Metadata_MtdtVal) ProtoReflect() protoreflect.Message {
	mi := &file_micropayment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata_MtdtVal.ProtoReflect.Descriptor instead.
func (*Metadata_MtdtVal) Descriptor() ([]byte, []int) {
	return file_micropayment_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Metadata_MtdtVal) GetIncludeSignature() bool {
	if x != nil {
		return x.IncludeSignature
	}
	return false
}

func (m *Metadata_MtdtVal) GetVal() isMetadata_MtdtVal_Val {
	if m != nil {
		return m.Val
	}
	return nil
}

func (x *Metadata_MtdtVal) GetIntVal() int32 {
	if x, ok := x.GetVal().(*Metadata_MtdtVal_IntVal); ok {
		return x.IntVal
	}
	return 0
}

func (x *Metadata_MtdtVal) GetStrVal() string {
	if x, ok := x.GetVal().(*Metadata_MtdtVal_StrVal); ok {
		return x.StrVal
	}
	return ""
}

type isMetadata_MtdtVal_Val interface {
	isMetadata_MtdtVal_Val()
}

type Metadata_MtdtVal_IntVal struct {
	IntVal int32 `protobuf:"varint,2,opt,name=int_val,json=intVal,proto3,oneof"`
}

type Metadata_MtdtVal_StrVal struct {
	StrVal string `protobuf:"bytes,3,opt,name=str_val,json=strVal,proto3,oneof"`
}

func (*Metadata_MtdtVal_IntVal) isMetadata_MtdtVal_Val() {}

func (*Metadata_MtdtVal_StrVal) isMetadata_MtdtVal_Val() {}

var File_micropayment_proto protoreflect.FileDescriptor

var file_micropayment_proto_rawDesc = []byte{
	0x0a, 0x12, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x22, 0xab, 0x01, 0x0a, 0x09, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x54, 0x78, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x61, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x69, 0x6c, 0x6c, 0x69, 0x6e, 0x67, 0x5f,
	0x63, 0x79, 0x63, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x62, 0x69, 0x6c,
	0x6c, 0x69, 0x6e, 0x67, 0x43, 0x79, 0x63, 0x6c, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x78, 0x6e,
	0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x78, 0x6e,
	0x48, 0x61, 0x73, 0x68, 0x12, 0x2a, 0x0a, 0x04, 0x6d, 0x74, 0x64, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x52, 0x04, 0x6d, 0x74, 0x64, 0x74,
	0x22, 0x8e, 0x02, 0x0a, 0x08, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x34, 0x0a,
	0x04, 0x76, 0x61, 0x6c, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x2e, 0x56, 0x61, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x76,
	0x61, 0x6c, 0x73, 0x1a, 0x73, 0x0a, 0x07, 0x4d, 0x74, 0x64, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x2b,
	0x0a, 0x11, 0x69, 0x6e, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x5f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x10, 0x69, 0x6e, 0x63, 0x6c, 0x75,
	0x64, 0x65, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x19, 0x0a, 0x07, 0x69,
	0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x06,
	0x69, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x12, 0x19, 0x0a, 0x07, 0x73, 0x74, 0x72, 0x5f, 0x76, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x06, 0x73, 0x74, 0x72, 0x56, 0x61,
	0x6c, 0x42, 0x05, 0x0a, 0x03, 0x56, 0x61, 0x6c, 0x1a, 0x57, 0x0a, 0x09, 0x56, 0x61, 0x6c, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x70, 0x61,
	0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4d,
	0x74, 0x64, 0x74, 0x56, 0x61, 0x6c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_micropayment_proto_rawDescOnce sync.Once
	file_micropayment_proto_rawDescData = file_micropayment_proto_rawDesc
)

func file_micropayment_proto_rawDescGZIP() []byte {
	file_micropayment_proto_rawDescOnce.Do(func() {
		file_micropayment_proto_rawDescData = protoimpl.X.CompressGZIP(file_micropayment_proto_rawDescData)
	})
	return file_micropayment_proto_rawDescData
}

var file_micropayment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_micropayment_proto_goTypes = []interface{}{
	(*SignedTxn)(nil),        // 0: micropayment.SignedTxn
	(*Metadata)(nil),         // 1: micropayment.Metadata
	(*Metadata_MtdtVal)(nil), // 2: micropayment.Metadata.MtdtVal
	nil,                      // 3: micropayment.Metadata.ValsEntry
}
var file_micropayment_proto_depIdxs = []int32{
	1, // 0: micropayment.SignedTxn.mtdt:type_name -> micropayment.Metadata
	3, // 1: micropayment.Metadata.vals:type_name -> micropayment.Metadata.ValsEntry
	2, // 2: micropayment.Metadata.ValsEntry.value:type_name -> micropayment.Metadata.MtdtVal
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_micropayment_proto_init() }
func file_micropayment_proto_init() {
	if File_micropayment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_micropayment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SignedTxn); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micropayment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micropayment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Metadata_MtdtVal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_micropayment_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Metadata_MtdtVal_IntVal)(nil),
		(*Metadata_MtdtVal_StrVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_micropayment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_micropayment_proto_goTypes,
		DependencyIndexes: file_micropayment_proto_depIdxs,
		MessageInfos:      file_micropayment_proto_msgTypes,
	}.Build()
	File_micropayment_proto = out.File
	file_micropayment_proto_rawDesc = nil
	file_micropayment_proto_goTypes = nil
	file_micropayment_proto_depIdxs = nil
}
